services:
  s1admin:
    image: dpage/pgadmin4
    container_name: 68-s1-admin
    ports:
      - ${ADMIN_PORT}
    environment:
      - PGADMIN_EMAIL=${ADMIN_EMAIL}
      - PGADMIN_PASSWORD=${ADMIN_PASSWORD}
    